name: Build and release

on:
  push:
    branches: [ main, next ]
  pull_request:
    branches: [ next ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install and test
      run: |
        npm install

    - name: Build Mac
      run: |
        npx electron-forge make --targets @electron-forge/maker-zip --platform darwin --arch x64
        npx electron-forge make --targets @electron-forge/maker-zip --platform darwin --arch arm64

    - name: Build Linux
      run: |
        npx electron-forge make --targets @electron-forge/maker-zip --platform linux --arch x64

    - name: Build Windows
      run: |
        npx electron-forge make --targets @electron-forge/maker-zip --platform win32 --arch x64
        npx electron-forge make --targets @electron-forge/maker-zip --platform win32 --arch x86

    - uses: actions/upload-artifact@v2
      with:
        name: endless-sky-data-editor-linux-x64
        path: out/make/**
